CREATE TABLE "A01_TEST"
(
"A0000" VARCHAR2(120) NOT NULL,
"A0101" VARCHAR2(36),
"A0102" VARCHAR2(20),
"A0104" VARCHAR2(20),
"A0107" VARCHAR2(20),
"A0111A" VARCHAR2(200),
"A0114A" VARCHAR2(200),
"A0115A" VARCHAR2(120),
"A0117" VARCHAR2(20),
"A0128" VARCHAR2(120),
"A0134" VARCHAR2(20),
"A0140" VARCHAR2(100),
"A0141" VARCHAR2(20),
"TEST" TIMESTAMP(0),
"TEST2" VARCHAR2(20),
"VERSION" VARCHAR2(10)) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "A01_TEST" IS '人员基本信息集';
COMMENT ON COLUMN "A01_TEST"."A0000" IS '人员统一标识符';
COMMENT ON COLUMN "A01_TEST"."A0101" IS '姓名';
COMMENT ON COLUMN "A01_TEST"."A0102" IS '姓名拼音缩写';
COMMENT ON COLUMN "A01_TEST"."A0104" IS '性别代码';
COMMENT ON COLUMN "A01_TEST"."A0107" IS '出生日期';
COMMENT ON COLUMN "A01_TEST"."A0111A" IS '籍贯代码描述';
COMMENT ON COLUMN "A01_TEST"."A0114A" IS '出生地代码描述';
COMMENT ON COLUMN "A01_TEST"."A0115A" IS '成长地代码描述';
COMMENT ON COLUMN "A01_TEST"."A0117" IS '民族代码';
COMMENT ON COLUMN "A01_TEST"."A0128" IS '健康状况代码';
COMMENT ON COLUMN "A01_TEST"."A0134" IS '参加工作时间';
COMMENT ON COLUMN "A01_TEST"."A0140" IS '入党时间描述';
COMMENT ON COLUMN "A01_TEST"."A0141" IS '政治面貌代码';
COMMENT ON COLUMN "A01_TEST"."TEST" IS '日期格式校验';
COMMENT ON COLUMN "A01_TEST"."TEST2" IS '身份证格式校验';
COMMENT ON COLUMN "A01_TEST"."VERSION" IS 'version';

CREATE TABLE "S_ERRORLOG"
(
"LOGID" VARCHAR2(50) NOT NULL,
"LOGTIME" TIMESTAMP(0) NOT NULL,
"STACKMSG" CLOB,
"MESSAGE" VARCHAR2(2000),
"EXCEPTIONTYPE" VARCHAR2(400),
"USERGENT" VARCHAR2(1000) NOT NULL,
"IPADDR" VARCHAR2(200) NOT NULL,
"URL" VARCHAR2(2000) NOT NULL,
"COOKIE" VARCHAR2(2000),
"USERID" VARCHAR2(36),
CONSTRAINT "PK_S_ERRORLOG" NOT CLUSTER PRIMARY KEY("LOGID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "S_ERRORLOG" IS '[0047]就业公共服务(外网)-网站运行异常日志信息表';
COMMENT ON COLUMN "S_ERRORLOG"."COOKIE" IS '请求用户端信息';
COMMENT ON COLUMN "S_ERRORLOG"."EXCEPTIONTYPE" IS '网站运行异常类型名称';
COMMENT ON COLUMN "S_ERRORLOG"."IPADDR" IS '客户端设备IP地址';
COMMENT ON COLUMN "S_ERRORLOG"."LOGID" IS '网站运行异常日志内码(编码规则:UUID)';
COMMENT ON COLUMN "S_ERRORLOG"."LOGTIME" IS '异常发生时间';
COMMENT ON COLUMN "S_ERRORLOG"."MESSAGE" IS '网站运行异常日志标题';
COMMENT ON COLUMN "S_ERRORLOG"."STACKMSG" IS '异常栈信息描述';
COMMENT ON COLUMN "S_ERRORLOG"."URL" IS '请求统一资源定位地址';
COMMENT ON COLUMN "S_ERRORLOG"."USERGENT" IS '用户代理信息';
COMMENT ON COLUMN "S_ERRORLOG"."USERID" IS '用户id';

CREATE TABLE "S_LOG"
(
"LOGID" VARCHAR2(50) NOT NULL,
"LOGTYPE" VARCHAR2(20),
"MESSAGE" VARCHAR2(2000),
"LOGTIME" TIMESTAMP(0),
"COST" VARCHAR2(100),
"STACKMSG" CLOB,
"EXCEPTIONTYPE" VARCHAR2(100),
"USERGENT" VARCHAR2(1000) NOT NULL,
"IPADDR" VARCHAR2(200) NOT NULL,
"REFERER" VARCHAR2(1000),
"URL" VARCHAR2(1000) NOT NULL,
"USERID" VARCHAR2(36),
"COOKIE" VARCHAR2(1000),
"APPKEY" VARCHAR2(36),
"METHOD" VARCHAR2(200),
"SUCCESS" VARCHAR2(1000),
"RESPONSEMSG" CLOB,
"QUERYPARAM" CLOB,
"TOKEN" VARCHAR2(3900),
"INTERFACETYPE" VARCHAR2(36),
"INTERFACECODE" VARCHAR2(36),
CONSTRAINT "PK_S_LOG" NOT CLUSTER PRIMARY KEY("LOGID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "S_LOG" IS '公共接口之接口访问日志记录表';
COMMENT ON COLUMN "S_LOG"."APPKEY" IS '渠道编号';
COMMENT ON COLUMN "S_LOG"."COOKIE" IS '状态码';
COMMENT ON COLUMN "S_LOG"."COST" IS '请求耗费时间(毫秒)';
COMMENT ON COLUMN "S_LOG"."EXCEPTIONTYPE" IS '异常类型名称';
COMMENT ON COLUMN "S_LOG"."INTERFACECODE" IS '接口编号';
COMMENT ON COLUMN "S_LOG"."INTERFACETYPE" IS '服务编号';
COMMENT ON COLUMN "S_LOG"."IPADDR" IS '客户端ip地址';
COMMENT ON COLUMN "S_LOG"."LOGID" IS '日志编号(uuid)';
COMMENT ON COLUMN "S_LOG"."LOGTIME" IS '发生时间';
COMMENT ON COLUMN "S_LOG"."LOGTYPE" IS '日志类型代码（1请求日志 2接口日志)';
COMMENT ON COLUMN "S_LOG"."MESSAGE" IS '日志标题';
COMMENT ON COLUMN "S_LOG"."METHOD" IS '请求方法类型名称';
COMMENT ON COLUMN "S_LOG"."QUERYPARAM" IS '请求参数信息';
COMMENT ON COLUMN "S_LOG"."REFERER" IS '地址来源';
COMMENT ON COLUMN "S_LOG"."RESPONSEMSG" IS '返回信息';
COMMENT ON COLUMN "S_LOG"."STACKMSG" IS '异常栈信息';
COMMENT ON COLUMN "S_LOG"."SUCCESS" IS '请求是否成功代码';
COMMENT ON COLUMN "S_LOG"."TOKEN" IS '请求jwt认证码';
COMMENT ON COLUMN "S_LOG"."URL" IS '请求的地址';
COMMENT ON COLUMN "S_LOG"."USERGENT" IS '代理信息';
COMMENT ON COLUMN "S_LOG"."USERID" IS '当前操作人员编号';

CREATE TABLE "S_FILE_RECORD"
(
"FILE_UUID" VARCHAR2(50) NOT NULL,
"FILE_NAME" VARCHAR2(200) NOT NULL,
"FILE_LENGTH" NUMBER(16,0) NOT NULL,
"FILE_ADDTIME" TIMESTAMP(0) NOT NULL,
"FILE_PATH" VARCHAR2(200) NOT NULL,
"FILE_STATUS" VARCHAR2(20) NOT NULL,
"FILE_TYPE" VARCHAR2(20) NOT NULL,
"FILE_REL_PATH" VARCHAR2(200) NOT NULL,
"FILE_BUS_ID" VARCHAR2(36),
"FILE_BUS_TYPE" VARCHAR2(20),
"BUS_ADDTIME" TIMESTAMP(0),
"FILE_BUS_NAME" VARCHAR2(200),
"FILE_BUS_DESCRIPTION" VARCHAR2(2000),
CONSTRAINT "PK_FILE" NOT CLUSTER PRIMARY KEY("FILE_UUID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "S_FILE_RECORD" IS '公共接口之文件上传记录表';
COMMENT ON COLUMN "S_FILE_RECORD"."BUS_ADDTIME" IS '业务发生时间';
COMMENT ON COLUMN "S_FILE_RECORD"."FILE_ADDTIME" IS '文件上传时间';
COMMENT ON COLUMN "S_FILE_RECORD"."FILE_BUS_DESCRIPTION" IS '业务上传文件描述';
COMMENT ON COLUMN "S_FILE_RECORD"."FILE_BUS_ID" IS '业务上传文件所属业务编号内码';
COMMENT ON COLUMN "S_FILE_RECORD"."FILE_BUS_NAME" IS '业务上传文件原名';
COMMENT ON COLUMN "S_FILE_RECORD"."FILE_BUS_TYPE" IS '业务上传文件所属业务业务类型代码';
COMMENT ON COLUMN "S_FILE_RECORD"."FILE_LENGTH" IS '文件大小单位(byte)';
COMMENT ON COLUMN "S_FILE_RECORD"."FILE_NAME" IS '文件名称';
COMMENT ON COLUMN "S_FILE_RECORD"."FILE_PATH" IS '文件上传绝对路径';
COMMENT ON COLUMN "S_FILE_RECORD"."FILE_REL_PATH" IS '文件上传相对路径';
COMMENT ON COLUMN "S_FILE_RECORD"."FILE_STATUS" IS '文件状态(0无效 1有效审核通过)';
COMMENT ON COLUMN "S_FILE_RECORD"."FILE_TYPE" IS '文件类型';
COMMENT ON COLUMN "S_FILE_RECORD"."FILE_UUID" IS '上传文件内码(编码规则:UUID)';
