CREATE TABLE `a01_test` (
  `a0000` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `a0101` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `a0102` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `a0104` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `a0107` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `a0111a` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `a0114a` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `a0115a` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `a0117` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `a0128` varchar(120) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `a0134` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `a0140` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `a0141` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `test` datetime DEFAULT NULL,
  `test2` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `version` varchar(10) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `s_errorlog` (
  `logid` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `logtime` datetime NOT NULL,
  `stackmsg` longtext CHARACTER SET utf8 COLLATE utf8_bin,
  `message` varchar(2000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `exceptiontype` varchar(400) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `usergent` varchar(1000) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `ipaddr` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `url` varchar(2000) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `cookie` varchar(2000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `userid` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`logid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `s_file_record` (
  `file_uuid` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `file_name` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `file_length` bigint(16) NOT NULL,
  `file_addtime` datetime NOT NULL,
  `file_path` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `file_status` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `file_type` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `file_rel_path` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `file_bus_id` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `file_bus_type` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `bus_addtime` datetime DEFAULT NULL,
  `file_bus_name` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `file_bus_description` varchar(2000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`file_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `s_log` (
  `logid` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `logtype` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `message` varchar(2000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `logtime` datetime DEFAULT NULL,
  `cost` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `stackmsg` longtext CHARACTER SET utf8 COLLATE utf8_bin,
  `exceptiontype` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `usergent` varchar(1000) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `ipaddr` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `referer` varchar(1000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `url` varchar(1000) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `userid` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `cookie` varchar(1000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `appkey` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `method` varchar(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `success` varchar(1000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `responsemsg` longtext CHARACTER SET utf8 COLLATE utf8_bin,
  `queryparam` longtext CHARACTER SET utf8 COLLATE utf8_bin,
  `token` varchar(4000) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `interfacetype` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `interfacecode` varchar(36) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`logid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
